apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Values.db.name }}
subsets:
  - addresses:
      - ip: {{ .Values.db.IP }}
    ports:
      - port: {{ .Values.db.port }}
        name: {{ .Values.db.name }}